// @vitest-environment node
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { flickMetadataOverlaySchema } from "../../packages/protocol/src/assetCatalogProtocol";
// Plain-JS ESM module (no type declarations); vitest transpiles the import fine.
import {
  CATALOG_PATH,
  DESIGNATION_NAME_EXCEPTIONS,
  OUTPUT_PATH,
  extractGltfPositionBounds,
  generateFlickMetadata,
} from "./generate-flick-metadata.mjs";

interface CatalogItem {
  category: string;
  fileName: string;
}

const overlayRaw = readFileSync(OUTPUT_PATH, "utf8");
const overlay = JSON.parse(overlayRaw) as {
  schema_version: number;
  generator: string;
  items: Record<
    string,
    {
      name_zh: string;
      aliases: string[];
      tags: string[];
      spatial: {
        bounds_m: [number, number, number];
        footprint_m: [number, number];
        height_m: number;
        ground_offset_y: number;
        front_axis: null;
      };
    }
  >;
};
const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8")) as { items: CatalogItem[] };
const catalogKeys = catalog.items.map((item) => `${item.category}/${item.fileName}`);

describe("flick-stage-props metadata.i18n.json", () => {
  it("parses with flickMetadataOverlaySchema", () => {
    const parsed = flickMetadataOverlaySchema.parse(overlay);
    expect(parsed.schema_version).toBe(1);
    expect(parsed.generator).toBe("tools/scripts/generate-flick-metadata.mjs");
  });

  it("covers every catalog item with no orphan keys", () => {
    const overlayKeys = Object.keys(overlay.items);
    expect(overlayKeys).toHaveLength(catalog.items.length);

    const catalogSet = new Set(catalogKeys);
    expect(catalogSet.size).toBe(catalog.items.length);
    for (const key of overlayKeys) {
      expect(catalogSet.has(key), `orphan overlay key not in catalog: ${key}`).toBe(true);
    }

    const overlaySet = new Set(overlayKeys);
    for (const key of catalogKeys) {
      expect(overlaySet.has(key), `catalog item missing from overlay: ${key}`).toBe(true);
    }
  });

  it("keeps every name_zh Chinese-led, modulo a small explicit designation exception list", () => {
    expect(DESIGNATION_NAME_EXCEPTIONS.length).toBeLessThanOrEqual(5);
    const cjkPattern = /[\u3400-\u9fff]/;
    for (const [key, entry] of Object.entries(overlay.items)) {
      if (DESIGNATION_NAME_EXCEPTIONS.includes(key)) continue;
      expect(cjkPattern.test(entry.name_zh), `${key} name_zh "${entry.name_zh}" contains no CJK character`).toBe(true);
    }
  });

  it("uses lowercase slug tags including the source category", () => {
    const slugPattern = /^[a-z0-9][a-z0-9-]*$/;
    for (const [key, entry] of Object.entries(overlay.items)) {
      const category = key.split("/", 1)[0];
      expect(entry.tags, `${key} tags must include source category`).toContain(category);
      for (const tag of entry.tags) {
        expect(slugPattern.test(tag), `${key} tag "${tag}" is not a lowercase slug`).toBe(true);
      }
    }
  });

  it("carries positive metric bounds for every packaged prop", () => {
    for (const [key, entry] of Object.entries(overlay.items)) {
      expect(
        entry.spatial.bounds_m.every((value) => value >= 0),
        `${key} bounds_m`,
      ).toBe(true);
      expect(Math.max(...entry.spatial.bounds_m), `${key} measurable bounds_m`).toBeGreaterThan(0);
      expect(entry.spatial.footprint_m).toEqual([entry.spatial.bounds_m[0], entry.spatial.bounds_m[2]]);
      expect(entry.spatial.height_m).toBe(entry.spatial.bounds_m[1]);
      expect(Number.isFinite(entry.spatial.ground_offset_y), `${key} ground_offset_y`).toBe(true);
    }
  });

  it("applies scene-node transforms when deriving model bounds", () => {
    expect(
      extractGltfPositionBounds({
        scenes: [{ nodes: [0] }],
        scene: 0,
        nodes: [{ mesh: 0, translation: [5, 0, 0], scale: [2, 3, 4] }],
        meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
        accessors: [{ min: [-1, 0, -0.5], max: [1, 2, 0.5] }],
      }),
    ).toEqual({ min: [3, 0, -2], max: [7, 6, 2] });
  });

  it.skipIf(!existsSync(join(dirname(CATALOG_PATH), "animals", "betta_fish.glb")))(
    "is regenerated byte-identically by generateFlickMetadata() (idempotent)",
    () => {
      const { json } = generateFlickMetadata();
      expect(json).toBe(overlayRaw);
    },
  );
});
