import { expect, type Locator, type Page } from "@playwright/test";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** Solid red 48x27 PNG generated by fixtures/generate-fixtures.mjs. */
export const FIXTURE_PNG_PATH = join(here, "fixtures", "director-e2e-red.png");
export const FIXTURE_PNG_NAME = "director-e2e-red";

/** ⌘Z on macOS, Ctrl+Z elsewhere (matches the app's meta/ctrl handling). */
export const UNDO_MODIFIER = process.platform === "darwin" ? "Meta" : "Control";

export const timelineRegion = (page: Page) => page.getByRole("region", { name: "视频时间线" });
export const timelineClips = (page: Page) => page.locator(".creative-timeline-clip");
export const videoTrackRow = (page: Page) => page.locator('[data-track-id="video-1"]');
export const playhead = (page: Page) => page.locator(".creative-timeline-playhead");
export const timelineRuler = (page: Page) => page.locator(".creative-timeline-ruler");

/**
 * Every test starts from a blank workspace. Playwright already gives each
 * test an isolated browser context; clearing localStorage before any app
 * code runs is extra insurance against persisted workspace state leaking in
 * (e.g. through a reused context in the future).
 */
export async function prepareCleanStorage(page: Page): Promise<void> {
  await page.addInitScript(() => {
    try {
      // Only wipe on the first document of this test: if the dev server
      // hot-reloads mid-test, in-flight state must survive the reload.
      if (!window.sessionStorage.getItem("__director_e2e_cleared")) {
        window.sessionStorage.setItem("__director_e2e_cleared", "1");
        window.localStorage.clear();
      }
      // The first-run welcome guide overlay intercepts all pointer events;
      // mark it as seen so tests exercise the editor, not the onboarding.
      window.localStorage.setItem("director.welcome-guide.v1.seen", "1");
    } catch {
      // Storage may be unavailable in restricted contexts; the app copes.
    }
  });
}

export async function openVideoEditor(page: Page): Promise<void> {
  await prepareCleanStorage(page);
  await page.goto("/?workspace=video");
  // Generous timeout: the lazy video-editor chunk is compiled on demand by Vite.
  await expect(timelineRegion(page)).toBeVisible({ timeout: 60_000 });
}

/** Imports the fixture PNG through the media panel's hidden file input. */
export async function importFixtureImage(page: Page): Promise<Locator> {
  await page.locator('input[type="file"][aria-label="导入素材"]').setInputFiles(FIXTURE_PNG_PATH);
  const card = page.getByRole("listitem").filter({ hasText: FIXTURE_PNG_NAME });
  await expect(card).toBeVisible({ timeout: 20_000 });
  return card;
}

/** Clicks the hover "+ 添加 <asset>" affordance on a media card. */
export async function addCardToTimeline(page: Page, card: Locator): Promise<void> {
  await card.hover();
  await card.getByRole("button", { name: /^添加/ }).click();
}

/** Pointer-scrubs the timeline ruler at `offsetX` px from its left edge. */
export async function scrubRulerAt(page: Page, offsetX: number): Promise<void> {
  const box = await timelineRuler(page).boundingBox();
  if (!box) throw new Error("时间线标尺不可见，无法刮擦");
  const y = box.y + box.height / 2;
  await page.mouse.move(box.x + Math.max(0, offsetX - 40), y);
  await page.mouse.down();
  await page.mouse.move(box.x + offsetX, y, { steps: 4 });
  await page.mouse.up();
}

/** Reads the resolved CSS `left` of a locator, in pixels. */
export async function cssLeftPx(target: Locator): Promise<number> {
  const value = await target.evaluate((element) => window.getComputedStyle(element).left);
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed)) throw new Error(`无法解析 left 值: ${value}`);
  return parsed;
}
