import type { DirectorWorldRiver } from "../../../../../../../packages/protocol/src/worldSystemsProtocol";

type Vec3 = readonly [number, number, number];

/**
 * Geometry buffers for a river ribbon generated by {@link buildRiverRibbonData}.
 *
 * The ribbon is a two-vertex-wide triangle strip swept through a Catmull-Rom
 * centerline. UV.x crosses the channel (0 = left bank, 1 = right bank); UV.y
 * is normalized arc length in channel-width units so flow textures keep a
 * stable metre scale.
 */
export interface RiverRibbonData {
  /** Vertex positions (world space), 3 floats per vertex. */
  positions: Float32Array;
  /** Vertex normals (world space), 3 floats per vertex. */
  normals: Float32Array;
  /** Texture coordinates: x = channel cross (0→1), y = arc length / width. */
  uvs: Float32Array;
  /** Flow direction tangents (world space), 3 floats per vertex. */
  flowTangents: Float32Array;
  /**
   * Per-vertex downhill slope (descent along the flow direction, ≥ 0),
   * 1 float per vertex. Uphill stretches read 0 — only water falling with
   * gravity churns into rapids.
   */
  slopes: Float32Array;
  /** Per-vertex curvature magnitude, 1 float per vertex. */
  curvatures: Float32Array;
  /**
   * Per-vertex width multiplier from `widthProfile` (1 when absent), 1 float
   * per vertex. Lets the shader speed flow up through narrows (continuity:
   * same discharge through a narrower channel means faster water).
   */
  widthFactors: Float32Array;
  /** Triangle-strip index buffer: two triangles per sample pair. */
  indices: Uint32Array;
  /** Number of cross-section samples along the centerline. */
  sampleCount: number;
  /** Total arc length of the centerline in metres. */
  totalLengthM: number;
}

interface RiverSample {
  point: [number, number, number];
  tangent: [number, number, number];
  normal: [number, number, number];
  lateral: [number, number, number];
  widthM: number;
  widthFactor: number;
  slope: number;
  curvature: number;
  distanceM: number;
}

const MIN_SEGMENTS_PER_SPAN = 4;
const MAX_SEGMENTS_PER_SPAN = 24;

function clamp(value: number, minimum: number, maximum: number) {
  return Math.min(maximum, Math.max(minimum, value));
}

function length3(value: Vec3) {
  return Math.hypot(value[0], value[1], value[2]);
}

function subtract(left: Vec3, right: Vec3): [number, number, number] {
  return [left[0] - right[0], left[1] - right[1], left[2] - right[2]];
}

function normalize3(value: Vec3, fallback: Vec3 = [0, 0, 1]): [number, number, number] {
  const length = length3(value);
  return length > 1e-7
    ? [value[0] / length, value[1] / length, value[2] / length]
    : [fallback[0], fallback[1], fallback[2]];
}

function catmullRom(p0: Vec3, p1: Vec3, p2: Vec3, p3: Vec3, t: number): [number, number, number] {
  const t2 = t * t;
  const t3 = t2 * t;
  return [0, 1, 2].map(
    (axis) =>
      0.5 *
      (2 * p1[axis] +
        (-p0[axis] + p2[axis]) * t +
        (2 * p0[axis] - 5 * p1[axis] + 4 * p2[axis] - p3[axis]) * t2 +
        (-p0[axis] + 3 * p1[axis] - 3 * p2[axis] + p3[axis]) * t3),
  ) as [number, number, number];
}

function catmullRomDerivative(p0: Vec3, p1: Vec3, p2: Vec3, p3: Vec3, t: number): [number, number, number] {
  const t2 = t * t;
  return [0, 1, 2].map(
    (axis) =>
      0.5 *
      (-p0[axis] +
        p2[axis] +
        2 * (2 * p0[axis] - 5 * p1[axis] + 4 * p2[axis] - p3[axis]) * t +
        3 * (-p0[axis] + 3 * p1[axis] - 3 * p2[axis] + p3[axis]) * t2),
  ) as [number, number, number];
}

function catmullRomSecondDerivative(p0: Vec3, p1: Vec3, p2: Vec3, p3: Vec3, t: number): [number, number, number] {
  return [0, 1, 2].map(
    (axis) =>
      2 * p0[axis] -
      5 * p1[axis] +
      4 * p2[axis] -
      p3[axis] +
      3 * (-p0[axis] + 3 * p1[axis] - 3 * p2[axis] + p3[axis]) * t,
  ) as [number, number, number];
}

function sampleWidthMultiplier(profile: readonly number[] | undefined, normalized: number) {
  if (!profile?.length) return 1;
  if (profile.length === 1) return profile[0] ?? 1;
  const cursor = clamp(normalized, 0, 1) * (profile.length - 1);
  const left = Math.floor(cursor);
  const right = Math.min(profile.length - 1, left + 1);
  const mix = cursor - left;
  return (profile[left] ?? 1) * (1 - mix) + (profile[right] ?? 1) * mix;
}

function createSample(
  river: DirectorWorldRiver,
  span: number,
  t: number,
  previous: RiverSample | undefined,
): RiverSample {
  const points = river.points;
  const p0 = points[Math.max(0, span - 1)]!;
  const p1 = points[span]!;
  const p2 = points[span + 1]!;
  const p3 = points[Math.min(points.length - 1, span + 2)]!;
  const point = catmullRom(p0, p1, p2, p3, t);
  const derivative = catmullRomDerivative(p0, p1, p2, p3, t);
  const tangent = normalize3(derivative, previous?.tangent);
  const horizontalLength = Math.hypot(tangent[0], tangent[2]);
  const lateral: [number, number, number] =
    horizontalLength > 1e-7
      ? [tangent[2] / horizontalLength, 0, -tangent[0] / horizontalLength]
      : (previous?.lateral ?? [1, 0, 0]);
  const normal = normalize3(
    [-tangent[1] * tangent[0], tangent[0] * tangent[0] + tangent[2] * tangent[2], -tangent[1] * tangent[2]],
    [0, 1, 0],
  );
  const second = catmullRomSecondDerivative(p0, p1, p2, p3, t);
  const derivativeHorizontal = Math.max(1e-5, Math.hypot(derivative[0], derivative[2]));
  const curvature = clamp(
    Math.abs(derivative[0] * second[2] - derivative[2] * second[0]) /
      (derivativeHorizontal * derivativeHorizontal * derivativeHorizontal),
    0,
    1,
  );
  const normalized = (span + t) / Math.max(1, points.length - 1);
  const widthFactor = sampleWidthMultiplier(river.widthProfile, normalized);
  const widthM = river.widthM * widthFactor;
  const distanceM = previous ? previous.distanceM + length3(subtract(point, previous.point)) : 0;
  return {
    point,
    tangent,
    normal,
    lateral,
    widthM,
    widthFactor,
    // Downhill descent only: flow runs along the tangent, so water is falling
    // exactly when tangent.y < 0. Uphill stretches must not read as rapids.
    slope: clamp(Math.max(0, -tangent[1]) / Math.max(horizontalLength, 1e-5), 0, 2),
    curvature,
    distanceM,
  };
}

/**
 * Sweeps a two-vertex ribbon through a Catmull-Rom centerline.
 * UV.x crosses the channel (0 left bank → 1 right bank); UV.y is normalized
 * arc length in channel-width units, so flow textures keep a stable metre scale.
 */
export function buildRiverRibbonData(river: DirectorWorldRiver): RiverRibbonData {
  const samples: RiverSample[] = [];
  for (let span = 0; span < river.points.length - 1; span += 1) {
    const chord = length3(subtract(river.points[span + 1]!, river.points[span]!));
    const segments = clamp(
      Math.ceil(chord / Math.max(0.75, river.widthM * 0.28)),
      MIN_SEGMENTS_PER_SPAN,
      MAX_SEGMENTS_PER_SPAN,
    );
    const start = span === 0 ? 0 : 1;
    for (let step = start; step <= segments; step += 1) {
      samples.push(createSample(river, span, step / segments, samples.at(-1)));
    }
  }

  const positions = new Float32Array(samples.length * 2 * 3);
  const normals = new Float32Array(samples.length * 2 * 3);
  const uvs = new Float32Array(samples.length * 2 * 2);
  const flowTangents = new Float32Array(samples.length * 2 * 3);
  const slopes = new Float32Array(samples.length * 2);
  const curvatures = new Float32Array(samples.length * 2);
  const widthFactors = new Float32Array(samples.length * 2);
  const uvScale = Math.max(river.widthM, 0.5);

  samples.forEach((sample, sampleIndex) => {
    for (let side = 0; side < 2; side += 1) {
      const vertex = sampleIndex * 2 + side;
      const sign = side === 0 ? 1 : -1;
      const halfWidth = sample.widthM * 0.5;
      positions[vertex * 3] = sample.point[0] + sample.lateral[0] * halfWidth * sign;
      positions[vertex * 3 + 1] = sample.point[1];
      positions[vertex * 3 + 2] = sample.point[2] + sample.lateral[2] * halfWidth * sign;
      normals.set(sample.normal, vertex * 3);
      flowTangents.set(sample.tangent, vertex * 3);
      uvs[vertex * 2] = side;
      uvs[vertex * 2 + 1] = sample.distanceM / uvScale;
      slopes[vertex] = sample.slope;
      curvatures[vertex] = sample.curvature;
      widthFactors[vertex] = sample.widthFactor;
    }
  });

  const indices = new Uint32Array(Math.max(0, samples.length - 1) * 6);
  for (let sample = 0; sample < samples.length - 1; sample += 1) {
    const left = sample * 2;
    const right = left + 1;
    const nextLeft = left + 2;
    const nextRight = left + 3;
    indices.set([left, right, nextLeft, right, nextRight, nextLeft], sample * 6);
  }

  return {
    positions,
    normals,
    uvs,
    flowTangents,
    slopes,
    curvatures,
    widthFactors,
    indices,
    sampleCount: samples.length,
    totalLengthM: samples.at(-1)?.distanceM ?? 0,
  };
}
